### PR TITLE
Fallback to original URL if the beginIndex is invalid

### LINKED ISSUE #18626: StringIndexOutOfBoundsException: PhotonUtils.getPhotonImageUrl
Sentry Issue: [JETPACK-ANDROID-1B8](https://a8c.sentry.io/issues/3705760187/?referrer=github_integration)

```
StringIndexOutOfBoundsException: String index out of range: -39
    at java.lang.String.substring(String.java:2064)
    at org.wordpress.android.util.PhotonUtils.getPhotonImageUrl(PhotonUtils.java:141)
    at org.wordpress.android.util.PhotonUtils.getPhotonImageUrl(PhotonUtils.java:42)
    at org.wordpress.android.ui.media.MediaPreviewFragment.loadImage(MediaPreviewFragment.java:261)
    at org.wordpress.android.ui.media.MediaPreviewFragment.onResume(MediaPreviewFragment.java:213)
...
(24 additional frame(s) were not displayed)

RuntimeException: Unable to resume activity {com.jetpack.android/org.wordpress.android.ui.media.MediaPreviewActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -39
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4240)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4272)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/18626

**WordPress-Android PR:** https://github.com/wordpress-mobile/WordPress-Android/pull/20459

## Description
Checks the begin index before calling the substring function to prevent the `StringIndexOutOfBoundsException`

## To test
I was not able to reproduce the issue but there are 5 different crashes rooting from this exception (see https://github.com/wordpress-mobile/WordPress-Android/issues/18626#issuecomment-1994469899)
I managed to fake one URL that reproduces the crash and added a test for it.

### CODE REVIEW

File: WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java [hunk 1]
```diff
@@ -138,6 +138,12 @@ public static String getPhotonImageUrl(String imageUrl, int width, int height, Q
             query += "&ssl=1";
         }
 
-        return "https://i0.wp.com/" + imageUrl.substring(schemePos + 3, imageUrl.length()) + query;
+        int beginIndex = schemePos + 3;
+        if (beginIndex < 0 || beginIndex > imageUrl.length()) {
+            // Fallback to original URL if the beginIndex is invalid to avoid `StringIndexOutOfBoundsException`
```
Comment (mkevins) [inline WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java:145]: NP: It seems that `imageUrl` is conditionally mutated a few times prior to this. Should we tweak this code comment to not mention "original" URL? Or, alternatively, if that is what we want, store it in a local var at the top of the function and return it here without mutation? 🤔

File: WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java [hunk 2]
```diff
@@ -138,6 +138,12 @@ public static String getPhotonImageUrl(String imageUrl, int width, int height, Q
...
+            // Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/18626
+            return imageUrl;
```
Comment (mkevins) [inline WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java]: Related to the above comment:

Does it make sense to re-include the query here?

**Review by mkevins — APPROVED** [review]
I left a couple of minor questions, but I consider them non-blocking, since I believe the implementation changes here are already an improvement over crashing out of bounds.

File: WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java (hunk 1 above)
Comment (antonis) [reply WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java:145]: That's a good suggestion @mkevins 👍 
In the other scheme error that the `imageUrl` is returned it hasn't been mutated yet. I think it makes sense to keep a copy of the url before any changes and return that.
I changed the code with e6b28eb2feacaf27fcb2196073be52688ce72e62

File: WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java (hunk 2 above)
Comment (antonis) [reply WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java]: Makes sense but this should be covered in the original url https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/143#discussion_r1524315898

Comment (mkevins) [reply WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java]: Nice!

**Comment by antonis** [comment]
Thank you for reviewing and your feedback @mkevins 🙇
